name: Scheduled Vercel Redeploy

on:
  schedule:
    - cron: "30 0 * * *" # Every day at 6am IST (00:30 UTC)
  workflow_dispatch:

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Trigger Vercel Redeploy
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        run: vercel deploy --prod --yes
